# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
