# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160709_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
    ]
